-- Auto-generated by scripts/build-addon-generated-data.py
-- Source: content/addon-content.sample.json
MidnightGuideGeneratedData = {
  version = "0.1.0",
  generatedAt = "2026-04-14T20:00:00Z",
  professions = {
    trackers = {
      {
        id = "midnight-profession-tracker",
        professionKey = "tailoring",
        title = {
          en = "Midnight Tailoring (knowledge)",
          nl = "Midnight Tailoring (kennis)"
        },
        treasures = {
          {
            id = "a-childs-stuffy",
            questId = 89078,
            name = {
              en = "A Child's Stuffy",
              nl = "A Child's Stuffy"
            },
            zone = {
              en = "Harandar",
              nl = "Harandar"
            },
            waypoint = {
              zone = "Harandar",
              way = "/way #2413 70.5 50.9 A Child's Stuffy (Tailoring)"
            }
          },
          {
            id = "a-really-nice-curtain",
            questId = 89079,
            name = {
              en = "A Really Nice Curtain",
              nl = "A Really Nice Curtain"
            },
            zone = {
              en = "Silvermoon City",
              nl = "Silvermoon City"
            },
            waypoint = {
              zone = "Silvermoon City",
              way = "/way #2393 35.9 61.3 A Really Nice Curtain (Tailoring)"
            }
          },
          {
            id = "sindorei-outfitters-ruler",
            questId = 89080,
            name = {
              en = "Sin'dorei Outfitter's Ruler",
              nl = "Sin'dorei Outfitter's Ruler"
            },
            zone = {
              en = "Eversong Woods",
              nl = "Eversong Woods"
            },
            waypoint = {
              zone = "Eversong Woods",
              way = "/way #2395 46.3 34.8 Sin'dorei Outfitter's Ruler (Tailoring)"
            }
          },
          {
            id = "wooden-weaving-sword",
            questId = 89081,
            name = {
              en = "Wooden Weaving Sword",
              nl = "Wooden Weaving Sword"
            },
            zone = {
              en = "Harandar",
              nl = "Harandar"
            },
            waypoint = {
              zone = "Harandar",
              way = "/way #2413 69.8 51.0 Wooden Weaving Sword (Tailoring)"
            }
          },
          {
            id = "book-of-sindorei-stitches",
            questId = 89082,
            name = {
              en = "Book of Sin'dorei Stitches",
              nl = "Book of Sin'dorei Stitches"
            },
            zone = {
              en = "Voidstorm — Slayer's Rise",
              nl = "Voidstorm — Slayer's Rise"
            },
            waypoint = {
              zone = "Voidstorm",
              way = "/way #2444 62.0 83.6 Book of Sin'dorei Stitches (Tailoring)"
            }
          },
          {
            id = "satin-throw-pillow",
            questId = 89083,
            name = {
              en = "Satin Throw Pillow",
              nl = "Satin Throw Pillow"
            },
            zone = {
              en = "Voidstorm — Slayer's Rise",
              nl = "Voidstorm — Slayer's Rise"
            },
            waypoint = {
              zone = "Voidstorm",
              way = "/way #2444 61.6 85.0 Satin Throw Pillow (Tailoring)"
            }
          },
          {
            id = "particularly-enchanting-tablecloth",
            questId = 89084,
            name = {
              en = "Particularly Enchanting Tablecloth",
              nl = "Particularly Enchanting Tablecloth"
            },
            zone = {
              en = "Silvermoon City",
              nl = "Silvermoon City"
            },
            waypoint = {
              zone = "Silvermoon City",
              way = "/way #2393 31.8 68.2 Particularly Enchanting Tablecloth (Tailoring)"
            }
          },
          {
            id = "artisans-cover-comb",
            questId = 89085,
            name = {
              en = "Artisan's Cover Comb",
              nl = "Artisan's Cover Comb"
            },
            zone = {
              en = "Zul'Aman",
              nl = "Zul'Aman"
            },
            waypoint = {
              zone = "Zul'Aman",
              way = "/way #2437 40.5 49.4 Artisan's Cover Comb (Tailoring)"
            }
          }
        },
        books = {
          {
            id = "skill-issue-tailoring",
            name = {
              en = "Skill Issue: Tailoring (renown vendor)",
              nl = "Skill Issue: Tailoring (renown-verkoper)"
            },
            zone = {
              en = "Eversong Woods — Caeris Fairdawn (Silvermoon Court Renown 6)",
              nl = "Eversong Woods — Caeris Fairdawn (Silvermoon Court Renown 6)"
            },
            waypoint = {
              zone = "Eversong Woods",
              way = "/way #2395 43.43 47.44 Skill Issue: Tailoring (75 Artisan Tailor's Moxie + 750 Voidlight Marl)"
            }
          }
        }
      }
    }
  },
  weekly = {
    tasks = {
      {
        id = "weekly-delve-4",
        title = {
          en = "Complete 4 Delves",
          nl = "Voltooi 4 Delves"
        },
        description = {
          en = "Account-wide progress for Great Vault.",
          nl = "Account-brede voortgang voor de Great Vault."
        },
        group = "delves",
        recommended = true
      }
    }
  },
  help = {
    install = {
      title = {
        en = "Midnight Guide — Installation",
        nl = "Midnight Guide — Installatie"
      },
      steps = {
        {
          id = "download-zip",
          text = {
            en = "Download the Midnight Guide addon ZIP (e.g. GitHub release or CI artifact).",
            nl = "Download de Midnight Guide addon-ZIP (bijv. GitHub-release of CI-artifact)."
          }
        },
        {
          id = "extract-folder",
          text = {
            en = "Extract so the folder MidnightGuide sits directly under Interface/AddOns (next to your other addons). The .toc file must be at AddOns/MidnightGuide/MidnightGuide.toc.",
            nl = "Pak uit zodat de map MidnightGuide direct onder Interface/AddOns staat (naast je andere addons). Het .toc-bestand moet op AddOns/MidnightGuide/MidnightGuide.toc staan."
          }
        },
        {
          id = "slash-command",
          text = {
            en = "In-game, type /mg to open or close the window. Subcommands: /mg help, /mg treasures, /mg books, /mg my-treasures, /mg my-books.",
            nl = "In-game: typ /mg om het venster te openen of te sluiten. Subcommando's: /mg help, /mg treasures, /mg books, /mg my-treasures, /mg my-books."
          }
        }
      },
      folderPath = "World of Warcraft\\_retail_\\Interface\\AddOns\\MidnightGuide\\"
    },
    troubleshooting = {
      {
        id = "addon-not-visible",
        text = {
          en = "If the addon does not appear in the AddOns list, confirm the MidnightGuide folder is inside Interface/AddOns and restart the game.",
          nl = "Als de addon niet in de AddOns-lijst staat: controleer of de map MidnightGuide in Interface/AddOns staat en herstart de game."
        }
      },
      {
        id = "nested-folder",
        text = {
          en = "Avoid extra nesting (e.g. AddOns/Midnight_guide-release/addon/MidnightGuide). WoW only loads AddOns/YourAddonName with the .toc at that level.",
          nl = "Vermijd extra nesten (bijv. AddOns/Midnight_guide-release/addon/MidnightGuide). WoW laadt alleen AddOns/JouwAddonNaam met het .toc op dat niveau."
        }
      },
      {
        id = "standalone-mpt",
        text = {
          en = "The standalone Midnight Profession Tracker addon uses /mpt. Midnight Guide uses /mg only — both can be installed if you rename folders to avoid clashes.",
          nl = "De losse Midnight Profession Tracker-addon gebruikt /mpt. Midnight Guide alleen /mg — beide kunnen naast elkaar als de mapnamen niet botsen."
        }
      }
    }
  }
}
