#!/usr/bin/env python3
"""
Generate addon/MidnightGuide/GeneratedData.lua from content/addon-content.sample.json.
"""

from __future__ import annotations

import json
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
SOURCE_PATH = REPO_ROOT / "content" / "addon-content.sample.json"
TARGET_PATH = REPO_ROOT / "addon" / "MidnightGuide" / "GeneratedData.lua"


def to_lua(value, indent_level: int = 0) -> str:
    indent = "  " * indent_level
    next_indent = "  " * (indent_level + 1)

    if value is None:
        return "nil"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, str):
        escaped = (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\r", "\\r")
            .replace("\n", "\\n")
        )
        return f'"{escaped}"'
    if isinstance(value, list):
        if not value:
            return "{}"
        rows = [f"{next_indent}{to_lua(item, indent_level + 1)}" for item in value]
        return "{\n" + ",\n".join(rows) + f"\n{indent}" + "}"
    if isinstance(value, dict):
        if not value:
            return "{}"
        rows = []
        for key, val in value.items():
            if key.isidentifier():
                lua_key = key
            else:
                escaped_key = key.replace('"', '\\"')
                lua_key = f'["{escaped_key}"]'
            rows.append(f"{next_indent}{lua_key} = {to_lua(val, indent_level + 1)}")
        return "{\n" + ",\n".join(rows) + f"\n{indent}" + "}"

    return "nil"


def main() -> None:
    if not SOURCE_PATH.exists():
        raise FileNotFoundError(f"Source JSON not found: {SOURCE_PATH}")

    data = json.loads(SOURCE_PATH.read_text(encoding="utf-8"))
    lua_table = to_lua(data)
    output = "\n".join(
        [
            "-- Auto-generated by scripts/build-addon-generated-data.py",
            "-- Source: content/addon-content.sample.json",
            f"MidnightGuideGeneratedData = {lua_table}",
            "",
        ]
    )
    TARGET_PATH.write_text(output, encoding="utf-8")
    print(f"Generated Lua data: {TARGET_PATH.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
